### ISSUE TITLE
Update Plask / Skia documentation

### ISSUE THREAD

**Issue by vorg** [deanm/plask#31]
E.g.

This doesn't exist anymore http://www.plask.org/docs/v2.0/api/all.html#skCanvas_eraseColor
```
SkCanvas#eraseColor(r, g, b, a)
```

But this does and it's not on the website http://www.plask.org/docs/v2.0/api/all.htm
```
SkCanvas#clear(r, g, b, a)
```

**Comment by deanm** [comment]
Done after moving documentation inline in v3.
