### ISSUE TITLE
Add SRGB_ALPHA

### ISSUE THREAD

**Issue by vorg** [deanm/plask#46]
In [webgl_constants](https://github.com/deanm/plask/blob/master/webgl_constants.h#L499) there are

```
WEBGL_CONSTANTS_EACH(SRGB, 0x8C40)
WEBGL_CONSTANTS_EACH(SRGB8, 0x8C41)
WEBGL_CONSTANTS_EACH(SRGB8_ALPHA8, 0x8C43)
```

but this one is missing

```
SRGB_ALPHA  = SRGB_ALPHA_EXT = 0x8C42
```

Any particular reason why?

**Comment by deanm** [comment]
https://www.khronos.org/registry/webgl/specs/latest/2.0/webgl2.idl

Missing how?  I don't see it in the webgl 2.0 spec, if it's in an extension then we need to see what's involved and support that extension

**Comment by vorg** [comment]
Weird. Its here https://www.khronos.org/registry/webgl/extensions/EXT_sRGB/ and they say i has been promoted to WebGL 2.0 core..hmm.

**Comment by deanm** [comment]
"Written against the WebGL API 1.0 specification.
Promoted to core in WebGL API 2.0 specification."

I think they meant that the spec was written as an extension to 1.0, and then was "promoted" to being also an extension to 2.0, not that it became part of 2.0 itself.

**Comment by deanm** [comment]
b9f8c40a15db76125ad848a08f3f34163b835d41

**Comment by vorg** [comment]
Thanks1
