### ISSUE TITLE
setFullscreen is not implemented?

### ISSUE THREAD

**Issue by vorg** [deanm/plask#50]
I have found set fullscreen in the docs but not in code http://www.plask.org/refv3.html#NSWindow_setFullscreen

Is this something still waiting for a push?

**Comment by deanm** [comment]
No it's there since July:

https://github.com/deanm/plask/commit/cf32ba59161c9bde981d1deeb656c59b36d82a6c

https://github.com/deanm/plask/blob/05b9116ce62928a8783128f15788f5b7592278d0/plask_bindings.mm#L4005
https://github.com/deanm/plask/blob/05b9116ce62928a8783128f15788f5b7592278d0/plask.js#L384
