### ISSUE TITLE
AVPlayer removeAll breaks texture?

### ISSUE THREAD

**Issue by vorg** [deanm/plask#53]
I'm trying to replace currently playing video with another one

This works but when the second video finished it starts first one (as expected)

``` javascript
this.player.appendFile(firstFile);
this.player.play();
....
this.player.appendFile(secondFile);
this.player.playNext()
var tex = this.player.currentFrameTexture();
```

If I clean the queue with `removeAll()` I can't get the texture from the second video. It stays null even though `currentDuration()` updates properly (which mean video started loading)

``` javascript
this.player.appendFile(firstFile);
this.player.play();
....
this.player.removeAll(); //X_X
this.player.appendFile(secondFile);
this.player.playNext()
var tex = this.player.currentFrameTexture();
//tex is forever null
```

**Comment by deanm** [comment]
Why playNext and not just play?

**Comment by vorg** [comment]
Ok, I removed `playNext/play` at all and just stick to `setRate` and it works
